name: Build and test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: "zulu"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with testing
        run: ./gradlew check --console rich --info

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests
          path: ./build/reports/tests/test

      - name: JaCoCo test report
        if: success()
        run: ./gradlew jacocoTestReport

      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: jacoco
          path: ./build/reports/jacoco/test
